spring:
  application:
    name: TaskManger

  datasource:
    username: root
    password: root
    url: jdbc:h2:file:./tasks_bd

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true

logging:
  file:
    name: logs/expiredTasks.logs
  level:
    root: off
    org.example.taskmanager.scheduler: info